

import 'package:mecapp/models/produto.dart';

class ProdutoRepository {
  static List<Produto> tabela = [
    Produto(arquivo:'MMB-2H05T.03-M-0005.pdf', pagina: 1, desenho: 'MMB-2H05T.03-M-0006', code_stock: 14403517, posicao: 1, quantidade_lista: 1, texto_breve: 'MANCAL (ITEM 44 AO 63)', quantidadade_estoque: 1, unidade_medida:'CJ'),
    Produto(arquivo:'MMB-2H05T.03-M-0005.pdf', pagina: 1, desenho: 'MMB-2H05T.03-M-0005-A', code_stock: 10345698, posicao: 2, quantidade_lista: 4, texto_breve: 'ARRUELA DE TRAVA', quantidadade_estoque: 3, unidade_medida: 'PC'),
    Produto(arquivo:'MMB-2H05T.03-M-0005.pdf', pagina: 1, desenho: 'MMB-2H05T.03-M-0005-A', code_stock: 10345646, posicao: 3, quantidade_lista: 4, texto_breve: 'PARAFUSO DE TRAVA + 1 PORCA', quantidadade_estoque: 1, unidade_medida: 'PC'),
    Produto(arquivo:'MMB-2H05T.03-M-0005.pdf', pagina: 1, desenho: 'MMB-2H05T.03-M-0005-A', code_stock: 14314654, posicao: 4, quantidade_lista: 4, texto_breve: 'PLACA DE ADVERTÊNCIA EXPLOSÃO', quantidadade_estoque: 2, unidade_medida: 'PC'),
    Produto(arquivo:'MMB-2H05T.03-M-0005.pdf', pagina: 1, desenho: 'MMB-2H05T.03-M-0005-A', code_stock: 14445353, posicao: 5, quantidade_lista: 1, texto_breve: 'PLACA DE ADVERTÊNCIA IÇAMENTO', quantidadade_estoque: 11, unidade_medida: 'PC'),
    Produto(arquivo:'MMB-2H05T.03-M-0005.pdf', pagina: 1, desenho: 'MMB-2H05T.03-M-0005-A', code_stock: 14025520, posicao: 6, quantidade_lista: 1, texto_breve: 'PLACA DE ADVERTÊNCIA REMOÇÃO DO ROTOR', quantidadade_estoque: 1, unidade_medida: 'PC'),
    Produto(arquivo:'MMB-2H05T.03-M-0005.pdf', pagina: 1, desenho: 'MMB-2H05T.03-M-0005-A', code_stock: 14354646, posicao: 7, quantidade_lista: 1, texto_breve: 'O’RING DA LUVA DO EIXO', quantidadade_estoque: 7, unidade_medida: 'PC'),
    Produto(arquivo:'MMB-2H05T.03-M-0005.pdf', pagina: 1, desenho: 'MMB-2H05T.03-M-0005-A', code_stock: 14258525, posicao: 8, quantidade_lista: 8, texto_breve: 'PRISIONEIRO DO REVESTIMENTO TRASEIRO', quantidadade_estoque: 3, unidade_medida: 'PC'),
    Produto(arquivo:'MMB-2H05T.03-M-0005.pdf', pagina: 1, desenho: 'MMB-2H05T.03-M-0005-A', code_stock: 14487878, posicao: 9, quantidade_lista: 1, texto_breve: 'REVESTIMENTO TRASEIRO', quantidadade_estoque: 11, unidade_medida: 'PC'),
    Produto(arquivo:'MMB-2H05T.03-M-0005.pdf', pagina: 1, desenho: 'MMB-2H05T.03-M-0005-A', code_stock: 14400000, posicao: 10, quantidade_lista: 1, texto_breve: 'CORPO TRASEIRO', quantidadade_estoque: 5, unidade_medida: 'PC'),
    Produto(arquivo:'MMB-2H05T.03-M-0005.pdf', pagina: 1, desenho: 'MMB-2H05T.03-M-0005-A', code_stock: 14355386, posicao: 11, quantidade_lista: 1, texto_breve: 'REVESTIMENTO TRASEIRO', quantidadade_estoque: 2, unidade_medida: 'PC'),
    Produto(arquivo: 'MMB-2H05T.03-M-0005.pdf', pagina: 1, desenho: 'MMB-2H05T.03-M-0005', code_stock: 14256346, posicao: 12, quantidade_lista: 1, texto_breve: 'ROTOR', quantidadade_estoque: 2, unidade_medida: 'PC'),
          
          
          
          
          
          
          
          
          
        
        Produto(
          arquivo: 'MMB-2H05T.03-M-0005.pdf',
          pagina: 1,
          desenho: 'MMB-2H05T.03-M-0005',
          code_stock: 14382164,
          posicao: 13,
          quantidade_lista: 1,
          texto_breve: 'CORPO DIANTEIRO',
          quantidadade_estoque: 5,
          unidade_medida: 'PC',
        ),
        Produto(
          arquivo: 'MMB-2H05T.03-M-0005.pdf',
          pagina: 1,
          desenho: 'MMB-2H05T.03-M-0005',
          code_stock: 14381009,
          posicao: 14,
          quantidade_lista: 1,
          texto_breve: 'REVESTIMENTO DIANTEIRO',
          quantidadade_estoque: 8,
          unidade_medida: 'PC',
        ),
        Produto(
          arquivo: 'MMB-2H05T.03-M-0005.pdf',
          pagina: 1,
          desenho: 'MMB-2H05T.03-M-0005',
          code_stock: 10394702,
          posicao: 15,
          quantidade_lista: 1,
          texto_breve: 'PLACA DE ATENÇÃO',
          quantidadade_estoque: 6,
          unidade_medida: 'PC',
        ),
        Produto(
          arquivo: 'MMB-2H05T.03-M-0005.pdf',
          pagina: 1,
          desenho: 'MMB-2H05T.03-M-0005',
          code_stock: 14043957,
          posicao: 16,
          quantidade_lista: 1,
          texto_breve: 'REVESTIMENTO DA SUCÇÃO',
          quantidadade_estoque: 5,
          unidade_medida: 'PC',
        ),
        Produto(
          arquivo: 'MMB-2H05T.03-M-0005.pdf',
          pagina: 1,
          desenho: 'MMB-2H05T.03-M-0005',
          code_stock: 14376349,
          posicao: 17,
          quantidade_lista: 2,
          texto_breve: 'CUNHA',
          quantidadade_estoque: 4,
          unidade_medida: 'PC',
        ),
        Produto(
          arquivo: 'MMB-2H05T.03-M-0005.pdf',
          pagina: 1,
          desenho: 'MMB-2H05T.03-M-0005',
          code_stock: 14376687,
          posicao: 18,
          quantidade_lista: 1,
          texto_breve: 'JUNTA DA SUCÇÃO',
          quantidadade_estoque: 9,
          unidade_medida: 'PC',
        ),
        Produto(
          arquivo: 'MMB-2H05T.03-M-0005.pdf',
          pagina: 1,
          desenho: 'MMB-2H05T.03-M-0005',
          code_stock: 14381138,
          posicao: 19,
          quantidade_lista: 6,
          texto_breve: 'PARAFUSO DO CORPO DIANTEIRO + 2 PORCAS',
          quantidadade_estoque: 1,
          unidade_medida: 'PC',
        ),
        Produto(
          arquivo: 'MMB-2H05T.03-M-0005.pdf',
          pagina: 1,
          desenho: 'MMB-2H05T.03-M-0005',
          code_stock: 14383279,
          posicao: 20,
          quantidade_lista: 1,
          texto_breve: 'PORCA DO PROTETOR DE RESPINGOS',
          quantidadade_estoque: 3,
          unidade_medida: 'PC',
        ),
        Produto(
          arquivo: 'MMB-2H05T.03-M-0005.pdf',
          pagina: 1,
          desenho: 'MMB-2H05T.03-M-0005',
          code_stock: 14376691,
          posicao: 21,
          quantidade_lista: 2,
          texto_breve: 'PARAFUSO DO PROTETOR DE RESPINGOS',
          quantidadade_estoque: 4,
          unidade_medida: 'PC',
        ),
        Produto(
          arquivo: 'MMB-2H05T.03-M-0005.pdf',
          pagina: 1,
          desenho: 'MMB-2H05T.03-M-0005',
          code_stock: 14383280,
          posicao: 22,
          quantidade_lista: 3,
          texto_breve: 'PRISIONEIRO DO CORPO TRASEIRO + 1 PORCA',
          quantidadade_estoque: 7,
          unidade_medida: 'PC',
        ),
        Produto(
          arquivo: 'MMB-2H05T.03-M-0005.pdf',
          pagina: 1,
          desenho: 'MMB-2H05T.03-M-0005',
          code_stock: 14077533,
          posicao: 23,
          quantidade_lista: 1,
          texto_breve: 'PARAFUSO DE AJUSTE + 3 PORCAS + 2 ARRUELAS',
          quantidadade_estoque: 7,
          unidade_medida: 'PC',
        ),
        Produto(
          arquivo: 'MMB-2H05T.03-M-0005.pdf',
          pagina: 1,
          desenho: 'MMB-2H05T.03-M-0005',
          code_stock: 14213429,
          posicao: 24,
          quantidade_lista: 1,
          texto_breve: 'BASE',
          quantidadade_estoque: 3,
          unidade_medida: 'PC',
        ),
        Produto(
          arquivo: 'MMB-2H05T.03-M-0005.pdf',
          pagina: 1,
          desenho: 'MMB-2H05T.03-M-0005',
          code_stock: 14046951,
          posicao: 25,
          quantidade_lista: 1,
          texto_breve: 'PLACA',
          quantidadade_estoque: 2,
          unidade_medida: 'PC',
        ),
        Produto(
          arquivo: 'MMB-2H05T.03-M-0005.pdf',
          pagina: 1,
          desenho: 'MMB-2H05T.03-M-0005',
          code_stock: 14150285,
          posicao: 27,
          quantidade_lista: 1,
          texto_breve: 'ESPAÇADOR DA FLANGE DA SUCÇÃO',
          quantidadade_estoque: 3,
          unidade_medida: 'PC',
        ),
        Produto(
          arquivo: 'MMB-2H05T.03-M-0005.pdf',
          pagina: 1,
          desenho: 'MMB-2H05T.03-M-0005',
          code_stock: 10702860,
          posicao: 31,
          quantidade_lista: 1,
          texto_breve: 'PROTETOR DE RESPINGOS',
          quantidadade_estoque: 1,
          unidade_medida: 'PC',
        ),
        Produto(
          arquivo: 'MMB-2H05T.03-M-0005.pdf',
          pagina: 1,
          desenho: 'MMB-2H05T.03-M-0005',
          code_stock: 10341303,
          posicao: 32,
          quantidade_lista: 1,
          texto_breve: 'PLUG',
          quantidadade_estoque: 5,
          unidade_medida: 'PC',
        ),
        Produto(
          arquivo: 'MMB-2H05T.03-M-0005.pdf',
          pagina: 1,
          desenho: 'MMB-2H05T.03-M-0005',
          code_stock: 14103262,
          posicao: 33,
          quantidade_lista: 1,
          texto_breve: 'SOBREPOSTA',
          quantidadade_estoque: 9,
          unidade_medida: 'PC',
        ),
        Produto(
          arquivo: 'MMB-2H05T.03-M-0005.pdf',
          pagina: 1,
          desenho: 'MMB-2H05T.03-M-0005',
          code_stock: 14103280,
          posicao: 34,
          quantidade_lista: 4,
          texto_breve: 'GAXETA',
          quantidadade_estoque: 6,
          unidade_medida: 'PC',
        ),
        Produto(
          arquivo: 'MMB-2H05T.03-M-0005.pdf',
          pagina: 1,
          desenho: 'MMB-2H05T.03-M-0005',
          code_stock: 14103285,
          posicao: 35,
          quantidade_lista: 1,
          texto_breve: 'O’RING DA CAIXA DE GAXETAS',
          quantidadade_estoque: 4,
          unidade_medida: 'PC',
        ),
        Produto(
          arquivo: 'MMB-2H05T.03-M-0005.pdf',
          pagina: 1,
          desenho: 'MMB-2H05T.03-M-0005',
          code_stock: 14280457,
          posicao: 36,
          quantidade_lista: 1,
          texto_breve: 'CAIXA DE GAXETAS',
          quantidadade_estoque: 5,
          unidade_medida: 'PC',
        ),
        Produto(
          arquivo: 'MMB-2H05T.03-M-0005.pdf',
          pagina: 1,
          desenho: 'MMB-2H05T.03-M-0005',
          code_stock: 10382461,
          posicao: 37,
          quantidade_lista: 1,
          texto_breve: '0’RING DO ROTOR',
          quantidadade_estoque: 7,
          unidade_medida: 'PC',
        ),
        Produto(
          arquivo: 'MMB-2H05T.03-M-0005.pdf',
          pagina: 1,
          desenho: 'MMB-2H05T.03-M-0005',
          code_stock: 14394862,
          posicao: 38,
          quantidade_lista: 1,
          texto_breve: 'LUVA DO EIXO',
          quantidadade_estoque: 2,
          unidade_medida: 'PC',
        ),
        Produto(
          arquivo: 'MMB-2H05T.03-M-0005.pdf',
          pagina: 1,
          desenho: 'MMB-2H05T.03-M-0005',
          code_stock: 14394858,
          posicao: 39,
          quantidade_lista: 1,
          texto_breve: 'ANEL RESTRITOR',
          quantidadade_estoque: 3,
          unidade_medida: 'PC',
        ),
        Produto(
          arquivo: 'MMB-2H05T.03-M-0005.pdf',
          pagina: 1,
          desenho: 'MMB-2H05T.03-M-0005',
          code_stock: 14394867,
          posicao: 40,
          quantidade_lista: 2,
          texto_breve: 'PARAFUSO DE APERTO DA SOBREPOSTA + 1 PORCA + 1 ARRUELA',
          quantidadade_estoque: 1,
          unidade_medida: 'PC',
        ),
        Produto(
          arquivo: 'MMB-2H05T.03-M-0005.pdf',
          pagina: 1,
          desenho: 'MMB-2H05T.03-M-0005',
          code_stock: 14394826,
          posicao: 41,
          quantidade_lista: 2,
          texto_breve: 'CHAPA DE RETENÇÃO',
          quantidadade_estoque: 8,
          unidade_medida: 'PC',
        ),
        Produto(
          arquivo: 'MMB-2H05T.03-M-0005.pdf',
          pagina: 1,
          desenho: 'MMB-2H05T.03-M-0005',
          code_stock: 14377213,
          posicao: 42,
          quantidade_lista: 2,
          texto_breve: 'PARAFUSO CHAPA DE RETENÇÃO',
          quantidadade_estoque: 6,
          unidade_medida: 'PC',
        ),

        // --- Novos itens do desenho/arquivo MMB-2H05T.03-M-0006 ---
        Produto(
          arquivo: 'MMB-2H05T.03-M-0006.pdf',
          pagina: 1,
          desenho: 'MMB-2H05T.03-M-0006',
          code_stock: 14383479,
          posicao: 1,
          quantidade_lista: 1,
          texto_breve: 'EIXO',
          quantidadade_estoque: 4,
          unidade_medida: 'PC',
        ),
        Produto(
          arquivo: 'MMB-2H05T.03-M-0006.pdf',
          pagina: 1,
          desenho: 'MMB-2H05T.03-M-0006',
          code_stock: 14376891,
          posicao: 2,
          quantidade_lista: 1,
          texto_breve: 'CHAVETA',
          quantidadade_estoque: 5,
          unidade_medida: 'PC',
        ),
        Produto(
          arquivo: 'MMB-2H05T.03-M-0006.pdf',
          pagina: 1,
          desenho: 'MMB-2H05T.03-M-0006',
          code_stock: 14383480,
          posicao: 46,
          quantidade_lista: 2,
          texto_breve: 'PARAFUSO DO LABIRINTO',
          quantidadade_estoque: 7,
          unidade_medida: 'PC',
        ),
        Produto(
          arquivo: 'MMB-2H05T.03-M-0006.pdf',
          pagina: 1,
          desenho: 'MMB-2H05T.03-M-0006',
          code_stock: 14077733,
          posicao: 47,
          quantidade_lista: 2,
          texto_breve: 'BICO GRAXEIRO',
          quantidadade_estoque: 2,
          unidade_medida: 'PC',
        ),
        Produto(
          arquivo: 'MMB-2H05T.03-M-0006.pdf',
          pagina: 1,
          desenho: 'MMB-2H05T.03-M-0006',
          code_stock: 14213629,
          posicao: 48,
          quantidade_lista: 1,
          texto_breve: 'PLACA DE IDENTIFICAÇÃO',
          quantidadade_estoque: 3,
          unidade_medida: 'PC',
        ),
        Produto(
          arquivo: 'MMB-2H05T.03-M-0006.pdf',
          pagina: 1,
          desenho: 'MMB-2H05T.03-M-0006',
          code_stock: 14047151,
          posicao: 49,
          quantidade_lista: 1,
          texto_breve: 'SETA',
          quantidadade_estoque: 1,
          unidade_medida: 'PC',
        ),
        Produto(
          arquivo: 'MMB-2H05T.03-M-0006.pdf',
          pagina: 1,
          desenho: 'MMB-2H05T.03-M-0006',
          code_stock: 14150485,
          posicao: 50,
          quantidade_lista: 16,
          texto_breve: 'ARRUELA USA',
          quantidadade_estoque: 8,
          unidade_medida: 'PC',
        ),
        Produto(
          arquivo: 'MMB-2H05T.03-M-0006.pdf',
          pagina: 1,
          desenho: 'MMB-2H05T.03-M-0006',
          code_stock: 10703060,
          posicao: 51,
          quantidade_lista: 2,
          texto_breve: 'BUJAO',
          quantidadade_estoque: 3,
          unidade_medida: 'PC',
        ),
        Produto(
          arquivo: 'MMB-2H05T.03-M-0006.pdf',
          pagina: 1,
          desenho: 'MMB-2H05T.03-M-0006',
          code_stock: 10341503,
          posicao: 52,
          quantidade_lista: 1,
          texto_breve: 'CAIXA DO MANCAL',
          quantidadade_estoque: 2,
          unidade_medida: 'PC',
        ),
        Produto(
          arquivo: 'MMB-2H05T.03-M-0006.pdf',
          pagina: 1,
          desenho: 'MMB-2H05T.03-M-0006',
          code_stock: 14103462,
          posicao: 53,
          quantidade_lista: 1,
          texto_breve: 'ROLAMENTO',
          quantidadade_estoque: 3,
          unidade_medida: 'PC',
        ),
        Produto(
          arquivo: 'MMB-2H05T.03-M-0006.pdf',
          pagina: 1,
          desenho: 'MMB-2H05T.03-M-0006',
          code_stock: 14103480,
          posicao: 54,
          quantidade_lista: 1,
          texto_breve: 'TAMPA DO MANCAL',
          quantidadade_estoque: 1,
          unidade_medida: 'PC',
        ),
        Produto(
          arquivo: 'MMB-2H05T.03-M-0006.pdf',
          pagina: 1,
          desenho: 'MMB-2H05T.03-M-0006',
          code_stock: 14103485,
          posicao: 55,
          quantidade_lista: 1,
          texto_breve: 'LABIRINTO',
          quantidadade_estoque: 5,
          unidade_medida: 'PC',
        ),
        Produto(
          arquivo: 'MMB-2H05T.03-M-0006.pdf',
          pagina: 1,
          desenho: 'MMB-2H05T.03-M-0006',
          code_stock: 14280657,
          posicao: 56,
          quantidade_lista: 1,
          texto_breve: 'LABIRINTO (LADO DO ACIONAMENTO)',
          quantidadade_estoque: 8,
          unidade_medida: 'PC',
        ),
        Produto(
          arquivo: 'MMB-2H05T.03-M-0006.pdf',
          pagina: 1,
          desenho: 'MMB-2H05T.03-M-0006',
          code_stock: 10382661,
          posicao: 57,
          quantidade_lista: 1,
          texto_breve: 'TAMPA DO MANCAL (LADO DO ACIONAMENTO)',
          quantidadade_estoque: 6,
          unidade_medida: 'PC',
        ),
        Produto(
          arquivo: 'MMB-2H05T.03-M-0006.pdf',
          pagina: 1,
          desenho: 'MMB-2H05T.03-M-0006',
          code_stock: 14395062,
          posicao: 58,
          quantidade_lista: 1,
          texto_breve: 'ROLAMENTO (LADO DO ACIONAMENTO)',
          quantidadade_estoque: 5,
          unidade_medida: 'PC',
        ),
        Produto(
          arquivo: 'MMB-2H05T.03-M-0006.pdf',
          pagina: 1,
          desenho: 'MMB-2H05T.03-M-0006',
          code_stock: 14395058,
          posicao: 59,
          quantidade_lista: 2,
          texto_breve: 'GUARNIÇÃO',
          quantidadade_estoque: 4,
          unidade_medida: 'PC',
        ),
        Produto(
          arquivo: 'MMB-2H05T.03-M-0006.pdf',
          pagina: 1,
          desenho: 'MMB-2H05T.03-M-0006',
          code_stock: 14395067,
          posicao: 60,
          quantidade_lista: 16,
          texto_breve: 'PARAFUSO DA TAMPA',
          quantidadade_estoque: 9,
          unidade_medida: 'PC',
        ),
        Produto(
          arquivo: 'MMB-2H05T.03-M-0006.pdf',
          pagina: 1,
          desenho: 'MMB-2H05T.03-M-0006',
          code_stock: 14395026,
          posicao: 61,
          quantidade_lista: 4,
          texto_breve: 'ANEL DE PISTÃO',
          quantidadade_estoque: 1,
          unidade_medida: 'PC',
        ),
        Produto(
          arquivo: 'MMB-2H05T.03-M-0006.pdf',
          pagina: 1,
          desenho: 'MMB-2H05T.03-M-0006',
          code_stock: 14377413,
          posicao: 62,
          quantidade_lista: 2,
          texto_breve: 'RETENTOR',
          quantidadade_estoque: 3,
          unidade_medida: 'PC',
        ),
        Produto(
          arquivo: 'MMB-2H05T.03-M-0006.pdf',
          pagina: 1,
          desenho: 'MMB-2H05T.03-M-0006',
          code_stock: 14459959,
          posicao: 63,
          quantidade_lista: 2,
          texto_breve: 'PLUG',
          quantidadade_estoque: 1,
          unidade_medida: 'PC',
        ),





  ];
}